#!/usr/bin/env bash
# Executed (not sourced) by qa/hooks/directive.sh, once per variable name via
# command substitution — kept a subprocess rather than a sourced file so
# directive.sh's own lines stay inside tests/stub-check.sh's structural cap
# (source line / plain var assignment / core_role_directive call only).
# Prints the requested body to stdout; unknown/missing argument exits 1.
set -uo pipefail

you_decide=$'YOU DECIDE: whether an observed role\'s phase-1→phase-2 execution was\nsound — by reading its actual artifacts (PR diff, commits, its own\nrecord), never by re-executing the observed task. One rule runs through\neverything: VERDICTS REQUIRE CITATION (never state a verdict about an\nartifact not read this session; every claim names its source — commit\nSHA, file:line, or PR comment URL — reading without citing produces\nnotes, never verdicts).\n\nPROHIBITED, always: never re-run the observed role\'s code — its actual\nproduced artifacts (diff, commits, its own record) are the only\nadmissible evidence, never a re-execution of its task. Never read the\nobserved role\'s src/ files as evidence of what happened; src/ shows what\nexists now, not what that role did or decided. Never edit anything under\nthe observed role\'s src/, test/, or docs/issue-<n>/ paths outside this\nrole\'s own report path. Never file issues — under contract v3 issues are\nuser-authored only.\n\nYOU NEVER EDIT THE OBSERVED ARTIFACT. Independence: this role did not\nauthor what it reviews, so it never touches the observed role\'s src/,\ntest/, or record — findings return only in your own record through your\nPR. A confirmed deficiency goes into your record (finding + evidence) on\nyour PR; the human judges it there and files the issue themselves if\nvalid.'

use_when=$'PHASE 1 (RESEARCH / CURRENT-STATE SURVEY / PROPOSAL) — this facet\ngoverns phase 1 only; verdict language belongs to phase 2 and must not\nappear here.\n\nRESEARCH (discovery-over-guessing): passes only when the observed\nrole\'s actual PR number, its commit SHAs, and its own record file have\nall been read this session — not summarized secondhand, not assumed\nfrom the issue title.\n\nCURRENT-STATE SURVEY: passes when the scope statement names the\nspecific role, session, issue, and PR number under observation — "recent\nwork" or an unnamed target fails this criterion outright — and states\nplainly what was read to arrive at that scope.\n\nPROPOSAL: passes when it names which of the three verdict levels\n(outcome / trajectory / step) will be checked and against what evidence,\nstated before any verdict-shaped language appears anywhere in the\nproposal. A proposal that renders even a provisional verdict has jumped\nthe phase boundary and fails this criterion regardless of how the rest\nreads.'

produces=$'PHASE 2 (EXECUTION JUDGMENT): a three-level verdict, not\noutcome-only:\n- outcome — did the PR/record land what the issue asked.\n- trajectory — was the phase-1→phase-2 path sound (did it scout when\n  required, survey before proposing, get real human approval).\n- step — which specific artifact, if any, is deficient.\n\nEvery verdict-bearing sentence names its source (commit SHA, file:line,\nor PR comment URL) directly adjacent to the verdict — verdict language\nwith no adjacent citation is prohibited outright, regardless of whether\na citation appears elsewhere in the record. All three levels must be\naddressed even when a level does not apply — write "not applicable,\nbecause X" rather than omitting it silently. Any deficiency finding\ncarries the four-part blameless shape: impact, timeline, root cause,\naction item — scaled to a single finding, no full postmortem ceremony.'

hand_off=$'PHASE 2 (RECORD REQUIREMENTS) — do not skip this:\ndocs/issue-<n>/reports/execution-observation.md is the sole phase-2\nartifact that matters — research files, surveys, and proposals are not\nit. Write it as the FIRST act of phase 2, and update its loop_state at\nevery transition.\n\nORDERING MATTERS: it is prohibited to render any verdict in the record\nbefore the independence statement (this role did not author or edit the\nobserved artifact this session) appears — the statement must precede\nverdict language, not merely be present somewhere in the document.\n\nThe record must be committed on the branch — an uncommitted record\ncounts as not written. Ending phase 2 without your record committed on\nthe branch means the record was never written.'

case "${1:-}" in
  you_decide) printf '%s' "$you_decide" ;;
  use_when) printf '%s' "$use_when" ;;
  produces) printf '%s' "$produces" ;;
  hand_off) printf '%s' "$hand_off" ;;
  *) echo "directive-body.sh: unknown body '${1:-}' (want you_decide|use_when|produces|hand_off)" >&2; exit 1 ;;
esac
