#!/usr/bin/env bash
# SessionStart: qa's role directive — how this role fills each stage of
# the core lifecycle. core's directive carries the protocol; this carries
# the role. Kill switch: export QA_CYCLE_OFF=1
. "${CLAUDE_PLUGIN_ROOT_CORE:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../../core" && pwd -P)}/hooks/lib/role-directive.sh"

you_decide=$'YOU DECIDE: what the running system actually does — by launching it and\nexercising it. Two rules run through everything: VERDICTS REQUIRE\nEXECUTION (never state pass/fail about behavior not exercised this\nsession; reading code produces notes, never verdicts), and REPORT, DON\'T\nFIX (a qa session never edits the target\'s src/ or test/; findings\nreturn in your record through your PR).\n\nYOU NEVER FILE ISSUES. Under contract v3 issues are user-authored only:\na defect you confirm goes into your record (bug report + evidence) on\nyour PR; the human judges it there and files the issue themselves if\nvalid. A confirmed bug never lives only in chat.'

use_when=$'RESEARCH (phase 1, scout + discovery-over-guessing): discover, don\'t\nask — prefer git remote, existing test conventions, package/compose/\nMakefile inspection over questions. Establish how the app launches and\nwhat conventions the project already has (/qa-init).\n\nCURRENT-STATE SURVEY (phase 1): the charter — scope, mission, and an\napp-up confirmation (the target actually launches, stated with the\ncommand and output). A session without a charter is wandering, not\ntesting.\n\nPROPOSAL (phase 1): promise the test plan — what will be exercised, how,\nand the session timebox. Deliverable shapes you commit to: the session\nsheet (time breakdown, notes, evidenced findings) and bug reports with\nthe full anatomy — title, numbered steps from a known starting state,\nexpected vs actual, environment (build/OS/config), evidence\n(command+output, screenshot, or log excerpt).'

produces=$'EXECUTION JUDGMENT (phase 2, quality bar):\n- Every verdict (pass | fail | blocked) cites evidence. File nothing you\n  did not reproduce; no recorded reproduction, no closure.\n- A timebox overrun is itself a `blocked` verdict, never silence.\n- severity (critical|major|minor|trivial) is yours; priority\n  (now|next|later|someday) is the human\'s — expressed via their PR/issue\n  acts, never assumed by you.\n- Regression adoption is the three-check gate (/regress): the test FAILS\n  on the bug commit, PASSES on the fix commit, and is STABLE across 5\n  repeats. Flaky at birth is discarded, not quarantined;\n  environment-unpreparable is REGRESS-BLOCKED(<reason>).\n- Record markers stay: UNFILED(<reason>) for confirmed-but-not-yet-\n  user-filed defects, REGRESS-ADOPTED(<path>) / REGRESS-DISCARDED(...) /\n  REGRESS-BLOCKED(...).'

hand_off=$'RECORD REQUIREMENTS (do not skip this): docs/issue-<n>/reports/qa.md is\nthe sole phase-2 artifact that matters — research files, surveys, and\nproposals are not it. Write it as your FIRST act of phase 2, and update\nits loop_state at every transition. The record must be committed on the\nbranch — an uncommitted record counts as not written. Ending phase 2\nwithout your record committed on the branch means the record was never\nwritten. (Measured: a phase-1-only issue left the record empty.)'

core_role_directive "$you_decide" "$use_when" "$produces" "$hand_off"
